import "@/styles/globals.scss";
import type { AppProps } from "next/app";
import { ThemeProvider, createTheme } from "@mui/material/styles";
import Head from "next/head";
import FooterComponent from "@/components/FooterComponent";

const theme = createTheme({
  palette: {
    primary: {
      main: "#0ce1d5", // Replace this with your desired primary color
    },
    secondary: {
      main: "#2a8f9c", // Replace this with your desired secondary color
    },
    info: {
      main: "#fff", // Replace this with your desired secondary color
    },
    // You can also customize other colors such as error, warning, info, success.
    // For example:
    // error: { main: '#f44336' },
    // warning: { main: '#ff9800' },
    // info: { main: '#607d8b' },
    // success: { main: '#4caf50' },
  },
});

export default function App({ Component, pageProps }: AppProps) {
  return (
    <ThemeProvider theme={theme}>
      <Head>
        <title>Espaço Renata Sanches</title>
        <link rel="icon" href="/assets/icons/logo.ico"></link>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Component {...pageProps} />
      <FooterComponent />
    </ThemeProvider>
  );
}
